# Generated by Django 4.2.6 on 2023-12-05 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_payment_customuser_payment_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='payment',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='payment_date',
        ),
    ]
