# Generated by Django 5.0 on 2023-12-15 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatserver', '0002_chatlist'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ChatList',
        ),
    ]
