# Generated by Django 4.2.6 on 2023-10-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0002_remove_tripplanning_budget_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripplanning',
            name='status',
        ),
        migrations.AddField(
            model_name='mainplace',
            name='is_show',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='mainplace',
            name='status',
            field=models.CharField(blank=True, choices=[('In Progress', 'In Progress'), ('Completed', 'Completed')], max_length=20, null=True),
        ),
    ]
