# Generated by Django 4.2.6 on 2023-10-18 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0003_remove_tripplanning_status_mainplace_is_show_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_to', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('a', 'Accepted'), ('p', 'Pending'), ('r', 'Rejected')], default='p', max_length=1)),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travel_manager.mainplace')),
            ],
        ),
    ]
