# Generated by Django 4.2.6 on 2023-10-19 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel_manager', '0004_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
